
// =============================================================================
// FASE 12 — EMOJIS AUTOMÁTICOS E ICONOS PERSONALIZADOS
// =============================================================================
const _NA_F12_EMOJI_RULES=[
  ['coca cola','🥤','bebida'],['gaseosa','🥤','bebida'],['refresco','🥤','bebida'],['agua mineral','💧','bebida'],['agua','💧','bebida'],['jugo','🧃','bebida'],['néctar','🧃','bebida'],['cerveza','🍺','bebida'],['vino','🍷','bebida'],['leche','🥛','lácteo'],['yogurt','🥛','lácteo'],['café','☕','bebida'],['cafe','☕','bebida'],['té','🫖','bebida'],['energizante','⚡','bebida'],['sporade','⚡','bebida'],['volt','⚡','bebida'],
  ['arroz','🍚','alimento'],['azúcar','🍬','alimento'],['azucar','🍬','alimento'],['aceite','🫗','alimento'],['pan','🍞','alimento'],['fideo','🍝','alimento'],['tallarín','🍝','alimento'],['tallarin','🍝','alimento'],['galleta','🍪','snack'],['chocolate','🍫','snack'],['sal ','🧂','alimento'],['sal','🧂','alimento'],['salsa','🥫','alimento'],['atún','🐟','alimento'],['atun','🐟','alimento'],['pollo','🍗','alimento'],['carne','🥩','alimento'],['huevo','🥚','alimento'],['queso','🧀','lácteo'],['mantequilla','🧈','lácteo'],['harina','🌾','alimento'],['avena','🌾','alimento'],['sopa','🍲','alimento'],['kirma','🍫','snack'],
  ['detergente','🧼','limpieza'],['jabón','🧼','limpieza'],['jabon','🧼','limpieza'],['papel higiénico','🧻','limpieza'],['papel higienico','🧻','limpieza'],['papel','🧻','limpieza'],['shampoo','🧴','cuidado'],['champú','🧴','cuidado'],['lejía','🧴','limpieza'],['lejia','🧴','limpieza'],['lavavajilla','🧽','limpieza'],['esponja','🧽','limpieza'],['escoba','🧹','limpieza'],['limpiador','🧹','limpieza'],
  ['papas fritas','🍟','snack'],['papas','🍟','snack'],['chicle','🍬','snack'],['adams','🍬','snack'],['caramelo','🍭','snack'],['chupetín','🍭','snack'],['chupetin','🍭','snack'],['maní','🥜','snack'],['mani','🥜','snack'],['lakis','🌶️','snack'],['snack','🍿','snack'],
  ['manzana','🍎','fruta'],['plátano','🍌','fruta'],['platano','🍌','fruta'],['banana','🍌','fruta'],['naranja','🍊','fruta'],['limón','🍋','fruta'],['limon','🍋','fruta'],['tomate','🍅','verdura'],['cebolla','🧅','verdura'],['papa ','🥔','verdura'],['papa','🥔','verdura'],['zanahoria','🥕','verdura'],['culantro','🌿','verdura'],
  ['cable','🔌','tecnología'],['cargador','🔋','tecnología'],['auricular','🎧','tecnología'],['audífono','🎧','tecnología'],['audifono','🎧','tecnología'],['batería','🔋','tecnología'],['bateria','🔋','tecnología'],['pila','🔋','tecnología'],['memoria','💾','tecnología'],['usb','💾','tecnología'],['celular','📱','tecnología'],['teléfono','📱','tecnología'],
  ['vela','🕯️','hogar'],['fósforo','🔥','hogar'],['fosforo','🔥','hogar'],['encendedor','🔥','hogar'],['bolsa','🛍️','hogar'],['táper','🥡','hogar'],['taper','🥡','hogar'],['vaso','🥤','hogar'],['plato','🍽️','hogar'],
  ['medicamento','💊','salud'],['pastilla','💊','salud'],['vendaje','🩹','salud'],['alcohol','🧴','salud'],['mascarilla','😷','salud'],['pañal','👶','bebé'],['panal','👶','bebé'],['bebé','👶','bebé'],
  ['cuaderno','📒','librería'],['lapicero','🖊️','librería'],['lápiz','✏️','librería'],['lapiz','✏️','librería'],['colores','🖍️','librería'],['pegamento','🧴','librería'],['sobre','✉️','librería'],['recarga','📲','servicio'],['free fire','💎','servicio'],['diamante','💎','servicio']
];
const _NA_F12_EMOJI_CATALOG=[...new Set(['📦','🥤','💧','🧃','🍺','🍷','🥛','☕','🫖','⚡','🍚','🍬','🫗','🍞','🍝','🍪','🍫','🧂','🥫','🐟','🍗','🥩','🥚','🧀','🧈','🌾','🍲','🧼','🧻','🧴','🧽','🧹','🍟','🍭','🥜','🌶️','🍿','🍎','🍌','🍊','🍋','🍅','🧅','🥔','🥕','🌿','🔌','🔋','🎧','💾','📱','🕯️','🔥','🛍️','🥡','🍽️','💊','🩹','😷','👶','📒','🖊️','✏️','🖍️','✉️','📲','💎','🧊','🧃','🧸','🧦','👕','👟','🧢','🪥','🧸','🎁','🔧','🔒','🪣','🧺','🪴','🌽','🍬'])];
let _naF12IconMode='auto',_naF12Drawing=false,_naF12LastPoint=null;
function _naF12Normalize(value){return String(value||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9ñ\s]/g,' ').replace(/\s+/g,' ').trim();}
function _naF12HasKeyword(name,key){const normalized=_naF12Normalize(key);return normalized&&(` ${name} `).includes(` ${normalized} `);}
function asignarEmojiAutomatico(nombreProducto){const name=_naF12Normalize(nombreProducto);if(!name)return'📦';for(const [key,emoji] of _NA_F12_EMOJI_RULES){if(_naF12HasKeyword(name,key))return emoji;}return'📦';}
function _naF12EmojiReason(nombreProducto){const name=_naF12Normalize(nombreProducto);for(const [key,emoji,group] of _NA_F12_EMOJI_RULES){if(_naF12HasKeyword(name,key))return{emoji,reason:`Coincidencia: ${key} · ${group}`};}return{emoji:'📦',reason:'Sin coincidencia específica; se usará el icono general'};}
function _naF12SetMode(mode){_naF12IconMode=mode;const labels={auto:'Automático',manual:'Emoji manual',image:'Imagen subida',custom:'Icono personalizado'},label=document.getElementById('pIconMode'),auto=document.getElementById('pIconAutoBtn');if(label)label.textContent=labels[mode]||'Manual';auto?.classList.toggle('active',mode==='auto');}
function _naF12RenderVisual(){const preview=document.getElementById('imgPreview'),remove=document.getElementById('pRemoveImageBtn'),icon=document.getElementById('pIcon')?.value||'📦',source=typeof imagenProducto==='string'&&/^data:image\/(?:png|jpeg|webp|gif);base64,/i.test(imagenProducto)?imagenProducto:null;if(!preview)return;preview.replaceChildren();if(source){const img=document.createElement('img');img.src=source;img.alt='Vista previa del producto';img.style.cssText='width:100%;height:100%;object-fit:cover;border-radius:8px';preview.appendChild(img);}else preview.textContent=icon;if(remove)remove.hidden=!source;}
function _naF12ProductNameChanged(){if(_naF12IconMode!=='auto'||imagenProducto)return;const field=document.getElementById('pIcon');if(field)field.value=asignarEmojiAutomatico(document.getElementById('pNombre')?.value);_naF12RenderVisual();}
function _naF12ManualIconChanged(){_naF12SetMode('manual');_naF12RenderVisual();}
function _naF12EnableAutoEmoji(){if(imagenProducto&&!confirm('¿Reemplazar la imagen actual por un emoji automático?'))return;if(imagenProducto){imagenProducto=null;const input=document.getElementById('pImagen');if(input)input.value='';}_naF12SetMode('auto');_naF12ProductNameChanged();}
function _naF12RemoveProductImage(){if(!imagenProducto)return;if(!confirm('¿Quitar la imagen o icono personalizado de este producto?'))return;imagenProducto=null;const input=document.getElementById('pImagen');if(input)input.value='';const predicted=asignarEmojiAutomatico(document.getElementById('pNombre')?.value),field=document.getElementById('pIcon');if(field&&!field.value)field.value=predicted;_naF12SetMode(field?.value===predicted?'auto':'manual');_naF12RenderVisual();}
function abrirSelectorEmoji(){const search=document.getElementById('emojiPickerSearch');if(search)search.value='';const info=_naF12EmojiReason(document.getElementById('pNombre')?.value),choice=document.getElementById('emojiAutoChoice'),reason=document.getElementById('emojiAutoReason');if(choice)choice.textContent=info.emoji;if(reason)reason.textContent=info.reason;_naF12RenderEmojiPicker('');document.getElementById('mEmojiPicker')?.classList.add('open');setTimeout(()=>search?.focus(),60);}
function _naF12RenderEmojiPicker(query=''){const grid=document.getElementById('emojiPickerGrid');if(!grid)return;const q=_naF12Normalize(query),related=new Map();for(const [key,emoji,group] of _NA_F12_EMOJI_RULES){if(!q||_naF12Normalize(key).includes(q)||_naF12Normalize(group).includes(q)||emoji===query.trim())related.set(emoji,key);}const emojis=q?[...related.keys()]:_NA_F12_EMOJI_CATALOG;grid.replaceChildren();if(!emojis.length){const empty=document.createElement('div');empty.className='emoji-empty';empty.textContent='No se encontraron emojis relacionados.';grid.appendChild(empty);return;}for(const emoji of emojis){const button=document.createElement('button');button.type='button';button.className='emoji-choice';button.textContent=emoji;button.title=related.get(emoji)||'Usar emoji';button.addEventListener('click',()=>_naF12ChooseEmoji(emoji));grid.appendChild(button);}}
function _naF12ChooseAutoSuggestion(){_naF12ChooseEmoji(_naF12EmojiReason(document.getElementById('pNombre')?.value).emoji,true);}
function _naF12ChooseEmoji(emoji,auto=false){if(imagenProducto&&!confirm('¿Usar este emoji en lugar de la imagen actual?'))return;if(imagenProducto){imagenProducto=null;const input=document.getElementById('pImagen');if(input)input.value='';}const field=document.getElementById('pIcon');if(field)field.value=emoji;_naF12SetMode(auto?'auto':'manual');_naF12RenderVisual();cerrarModal('mEmojiPicker');}
function _naF12Canvas(){return document.getElementById('iconDesignerCanvas');}
function _naF12RoundRect(ctx,x,y,w,h,r){const radius=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+radius,y);ctx.arcTo(x+w,y,x+w,y+h,radius);ctx.arcTo(x+w,y+h,x,y+h,radius);ctx.arcTo(x,y+h,x,y,radius);ctx.arcTo(x,y,x+w,y,radius);ctx.closePath();}
function _naF12DesignerReset(){const canvas=_naF12Canvas();if(!canvas)return;const ctx=canvas.getContext('2d'),bg=document.getElementById('iconBgColor')?.value||'#00bca4',shape=document.getElementById('iconShape')?.value||'rounded';ctx.clearRect(0,0,canvas.width,canvas.height);if(shape==='transparent')return;ctx.fillStyle=bg;if(shape==='circle'){ctx.beginPath();ctx.arc(128,128,122,0,Math.PI*2);ctx.fill();}else if(shape==='rounded'){_naF12RoundRect(ctx,6,6,244,244,42);ctx.fill();}else ctx.fillRect(0,0,256,256);}
function _naF12DesignerPoint(event){const canvas=_naF12Canvas(),rect=canvas.getBoundingClientRect();return{x:(event.clientX-rect.left)*canvas.width/rect.width,y:(event.clientY-rect.top)*canvas.height/rect.height};}
function _naF12DesignerDown(event){event.preventDefault();_naF12Drawing=true;_naF12LastPoint=_naF12DesignerPoint(event);event.currentTarget.setPointerCapture?.(event.pointerId);}
function _naF12DesignerMove(event){if(!_naF12Drawing)return;event.preventDefault();const canvas=_naF12Canvas(),ctx=canvas.getContext('2d'),point=_naF12DesignerPoint(event),size=Number(document.getElementById('iconBrush')?.value||12);ctx.strokeStyle=document.getElementById('iconFgColor')?.value||'#ffffff';ctx.lineWidth=size;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(_naF12LastPoint.x,_naF12LastPoint.y);ctx.lineTo(point.x,point.y);ctx.stroke();_naF12LastPoint=point;}
function _naF12DesignerUp(){_naF12Drawing=false;_naF12LastPoint=null;}
function _naF12Initials(){const words=String(document.getElementById('pNombre')?.value||'NA').trim().split(/\s+/).filter(Boolean);return(words.length>1?(words[0][0]+words[1][0]):words[0]?.slice(0,2)||'NA').toUpperCase();}
function _naF12DesignerAddText(){const canvas=_naF12Canvas(),ctx=canvas.getContext('2d'),input=document.getElementById('iconText'),text=String(input?.value||_naF12Initials()).trim().slice(0,3).toUpperCase();if(input&&!input.value)input.value=text;ctx.save();ctx.fillStyle=document.getElementById('iconFgColor')?.value||'#ffffff';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`900 ${text.length>=3?78:104}px Nunito, Arial, sans-serif`;ctx.fillText(text,128,134);ctx.restore();}
function _naF12DesignerLoadImage(input){const file=input.files?.[0];if(!file)return;if(!file.type.startsWith('image/')||file.size>5_000_000){toast('Selecciona una imagen válida de hasta 5 MB','error');input.value='';return;}const reader=new FileReader();reader.onload=e=>{const img=new Image();img.onload=()=>{const canvas=_naF12Canvas(),ctx=canvas.getContext('2d'),scale=Math.min(canvas.width/img.width,canvas.height/img.height),w=img.width*scale,h=img.height*scale;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,(canvas.width-w)/2,(canvas.height-h)/2,w,h);};img.onerror=()=>toast('No se pudo abrir el icono','error');img.src=e.target.result;};reader.readAsDataURL(file);}
function abrirCreadorIcono(){document.getElementById('mIconDesigner')?.classList.add('open');const text=document.getElementById('iconText');if(text)text.value=_naF12Initials();requestAnimationFrame(()=>{const canvas=_naF12Canvas();if(!canvas)return;if(imagenProducto){const img=new Image();img.onload=()=>{const ctx=canvas.getContext('2d');ctx.clearRect(0,0,256,256);ctx.drawImage(img,0,0,256,256);};img.onerror=_naF12DesignerReset;img.src=imagenProducto;}else{_naF12DesignerReset();_naF12DesignerAddText();}});}
function _naF12OptimizedCanvasData(canvas){let data='';try{data=canvas.toDataURL('image/webp',.86);}catch(error){data=canvas.toDataURL('image/png');}if(data.length<=180000)return data;const small=document.createElement('canvas');small.width=192;small.height=192;small.getContext('2d').drawImage(canvas,0,0,192,192);try{data=small.toDataURL('image/webp',.76);}catch(error){data=small.toDataURL('image/png');}return data;}
function _naF12SaveCustomIcon(){const canvas=_naF12Canvas();if(!canvas)return;const data=_naF12OptimizedCanvasData(canvas);if(!data||data.length>240000){toast('El icono es demasiado pesado; simplifica el dibujo','error');return;}imagenProducto=data;const icon=document.getElementById('pIcon');if(icon&&!icon.value)icon.value='🖼️';_naF12SetMode('custom');_naF12RenderVisual();cerrarModal('mIconDesigner');toast('Icono personalizado aplicado','success');}
function _naF12InferMode(product){if(product?.imagen)return'image';const predicted=asignarEmojiAutomatico(product?.name||'');return(product?.icon||'📦')===predicted?'auto':'manual';}
const _naF12BaseAbrirModalProd=abrirModalProd;
abrirModalProd=function(...args){const result=_naF12BaseAbrirModalProd.apply(this,args);_naF12SetMode('auto');_naF12ProductNameChanged();_naF12RenderVisual();return result;};
const _naF12BaseEditProd=editProd;
editProd=function(id,...args){const product=productos.find(p=>String(p.id)===String(id)),storedImage=product?.imagen||null;if(product)product.imagen=null;let result;try{result=_naF12BaseEditProd.call(this,id,...args);}finally{if(product)product.imagen=storedImage;}imagenProducto=storedImage;_naF12SetMode(_naF12InferMode(product));_naF12RenderVisual();return result;};
const _naF12BasePreviewImagen=previewImagen;
previewImagen=function(...args){_naF12SetMode('image');const result=_naF12BasePreviewImagen.apply(this,args);setTimeout(_naF12RenderVisual,80);setTimeout(_naF12RenderVisual,350);setTimeout(_naF12RenderVisual,1000);return result;};
const _naF12BaseGuardarProd=guardarProd;
guardarProd=async function(...args){const icon=document.getElementById('pIcon');if(icon&&!icon.value.trim())icon.value=asignarEmojiAutomatico(document.getElementById('pNombre')?.value);return await _naF12BaseGuardarProd.apply(this,args);};
document.addEventListener('DOMContentLoaded',()=>{const canvas=_naF12Canvas();canvas?.addEventListener('pointerdown',_naF12DesignerDown);canvas?.addEventListener('pointermove',_naF12DesignerMove);canvas?.addEventListener('pointerup',_naF12DesignerUp);canvas?.addEventListener('pointercancel',_naF12DesignerUp);canvas?.addEventListener('pointerleave',_naF12DesignerUp);_naF12RenderVisual();});
