
// NUEVO FASE 9 — motor de reposición informativa. No crea compras ni modifica stock.
function _naF9Settings(){const base={historyDays:90,coverageDays:30,safetyDays:7},raw=appConfig.purchaseSuggestion||{};appConfig.purchaseSuggestion={historyDays:Math.max(30,Math.min(365,_naInt(raw.historyDays,base.historyDays))),coverageDays:Math.max(7,Math.min(180,_naInt(raw.coverageDays,base.coverageDays))),safetyDays:Math.max(0,Math.min(60,_naInt(raw.safetyDays,base.safetyDays)))};return appConfig.purchaseSuggestion;}
function _naF9Date(value){if(!value)return null;const d=new Date(String(value).slice(0,10)+'T12:00:00');return Number.isNaN(d.getTime())?null:d;}
function _naF9DaysBetween(a,b){return Math.floor((b-a)/86400000);}
function _naF9PurchaseUnitLabel(value){return({unidad:'unidades',caja:'cajas',paquete:'paquetes',sixpack:'sixpacks',fardo:'fardos',docena:'docenas',bolsa:'bolsas',otro:'presentaciones'})[value]||'presentaciones';}
function _naF9SaleDate(sale){return _naF9Date(sale?.fecha)||(()=>{const d=new Date(sale?.timestamp||'');return Number.isNaN(d.getTime())?null:d;})();}
function _naF9ProductSales(product,historyDays){const today=_naF9Date(obtenerHoy()),cutoff=new Date(today);cutoff.setDate(cutoff.getDate()-historyDays+1);let units=0,transactions=0,first=null,last=null;for(const sale of ventas){if(sale?.anulada)continue;const date=_naF9SaleDate(sale);if(!date||date<cutoff||date>today)continue;let found=false;for(const item of Array.isArray(sale.items)?sale.items:[]){const id=item?.productoId??item?.id,match=String(id)===String(product.id)||(!id&&_naClean(item?.sku).toLowerCase()===_naClean(product.sku).toLowerCase());if(!match)continue;units+=_naUnitsSold(item);found=true;}if(found){transactions++;if(!first||date<first)first=date;if(!last||date>last)last=date;}}const observed=first?Math.max(14,Math.min(historyDays,_naF9DaysBetween(first,today)+1)):historyDays;return{units:Number(units.toFixed(3)),transactions,first,last,observedDays:observed,avgDaily:units/Math.max(1,observed)};}
function _naF9Rotation(avgDaily){const monthly=avgDaily*30;if(monthly>=30)return{key:'alta',label:'Alta rotación',className:'good'};if(monthly>=8)return{key:'media',label:'Rotación media',className:'soon'};if(monthly>0)return{key:'baja',label:'Baja rotación',className:'review'};return{key:'sin_historial',label:'Sin historial',className:'review'};}
function _naF9AnalyzeProduct(product){
  const cfg=_naF9Settings(),sales=_naF9ProductSales(product,cfg.historyDays),stock=_naNumber(product.stock),availableStock=Math.max(0,stock),stockMin=Math.max(0,_naNumber(product.stockMin)),avg=sales.avgDaily,coverage=avg>0?availableStock/avg:null,expiry=diasHasta(product.venc),rotation=_naF9Rotation(avg),unitPurchase=_naClean(product.unidadCompra||(product.unidCaja?'caja':'unidad'))||'unidad',factor=unitPurchase==='unidad'?1:Math.max(.001,_naNumber(product.factorCompra,product.unidCaja||1)),target=Math.max(stockMin,avg*(cfg.coverageDays+cfg.safetyDays));
  let rawNeed=Math.max(0,target-stock),maxSafeAdd=Infinity,expiryRisk=false;
  if(expiry!==null){const safeDays=Math.max(0,expiry-cfg.safetyDays),safeInventory=avg>0?avg*safeDays:0;maxSafeAdd=Math.max(0,safeInventory-stock);if(rawNeed>maxSafeAdd){rawNeed=maxSafeAdd;expiryRisk=true;}}
  if(avg<=0||expiry!==null&&expiry<0)rawNeed=0;
  let suggestedUnits=0;
  if(rawNeed>0){suggestedUnits=Math.ceil(rawNeed/factor)*factor;if(Number.isFinite(maxSafeAdd)&&suggestedUnits>maxSafeAdd+.001)suggestedUnits=Math.floor(maxSafeAdd/factor)*factor;if(unitPurchase==='unidad'&&suggestedUnits<=0)suggestedUnits=Math.floor(maxSafeAdd>0?Math.min(rawNeed,maxSafeAdd):rawNeed);}
  suggestedUnits=Math.max(0,Number(suggestedUnits.toFixed(3)));
  const packages=factor>0?suggestedUnits/factor:0,investment=suggestedUnits*Math.max(0,_naNumber(product.costo)),potentialRevenue=suggestedUnits*Math.max(0,_naNumber(product.precio)),potentialProfit=Math.max(0,potentialRevenue-investment),daysToSellSuggested=avg>0?suggestedUnits/avg:null,overstock=expiry!==null&&avg>0&&coverage!==null&&coverage>Math.max(0,expiry-cfg.safetyDays),need=stock<=stockMin||coverage!==null&&coverage<=cfg.coverageDays||suggestedUnits>0||overstock||expiryRisk;
  let priority='ok',priorityLabel='Stock suficiente',reason='El stock cubre el período configurado.';
  if(expiry!==null&&expiry<0){priority='review';priorityLabel='No comprar';reason='El producto está vencido. Revisa merma y retiro del inventario.';}
  else if(avg<=0){priority='review';priorityLabel='Revisar';reason=stock<=stockMin?'No hay historial de ventas suficiente para recomendar una compra automática.':'Sin ventas recientes; evita inmovilizar capital.';}
  else if(overstock){priority='review';priorityLabel='Riesgo de vencimiento';reason='El stock actual podría durar más que el tiempo útil antes del vencimiento.';}
  else if(stock<=0||coverage<=7){priority='urgent';priorityLabel='Reposición urgente';reason='El producto tiene poco o ningún stock frente a su ritmo de venta.';}
  else if(coverage<=cfg.coverageDays){priority='soon';priorityLabel='Comprar pronto';reason=`El stock cubre aproximadamente ${Math.max(0,coverage).toFixed(1)} días.`;}
  else if(expiryRisk){priority='review';priorityLabel='Compra limitada';reason='La fecha de vencimiento limita la cantidad segura a comprar.';}
  return{product,cfg,sales,stock,stockMin,avg,coverage,expiry,rotation,unitPurchase,factor,suggestedUnits,packages,investment,potentialRevenue,potentialProfit,daysToSellSuggested,overstock,expiryRisk,need,priority,priorityLabel,reason};
}
function _naF9All(){return productos.filter(_naTracksStock).map(_naF9AnalyzeProduct);}
function _naF9Visible(){const q=sinTildes((document.getElementById('invSearch')?.value||'').toLowerCase()),cat=document.getElementById('invCat')?.value||'';return _naF9All().filter(a=>a.need&&(!cat||a.product.cat===cat)&&(!q||[a.product.name,a.product.sku,a.product.barcode,a.product.marca].some(v=>sinTildes(String(v||'').toLowerCase()).includes(q)))).sort((a,b)=>{const rank={urgent:0,soon:1,review:2,ok:3};return rank[a.priority]-rank[b.priority]||b.avg-a.avg||b.potentialProfit-a.potentialProfit;});}
function _naF9Summary(rows){return{urgent:rows.filter(r=>r.priority==='urgent').length,high:rows.filter(r=>r.rotation.key==='alta').length,risk:rows.filter(r=>r.overstock||r.expiryRisk).length,investment:rows.reduce((s,r)=>s+r.investment,0)};}
function _naF9Card(a){const p=a.product,idToken=encodeURIComponent(String(p.id)).replace(/'/g,'%27'),stockLabel=`${Number(a.stock.toFixed(3))} ${_naCategoryTitle(p.unidad||'unidad').toLowerCase()}`,coverage=a.coverage===null?'Sin historial':`${a.coverage.toFixed(1)} días`,expiry=a.expiry===null?'Sin fecha':a.expiry<0?`Vencido ${Math.abs(a.expiry)}d`:a.expiry===0?'Vence hoy':`${a.expiry} días`,purchaseLabel=a.suggestedUnits>0?`${Number(a.packages.toFixed(2))} ${_naF9PurchaseUnitLabel(a.unitPurchase)} · ${Number(a.suggestedUnits.toFixed(2))} unidades`:'No comprar automáticamente',icon=p.imagen?`<img src="${_naEsc(p.imagen)}" alt="">`:_naEsc(p.icon||'📦');return`<article class="purchase-card ${a.priority==='urgent'?'urgent':a.overstock||a.expiryRisk?'risk':a.priority==='ok'?'good':''}"><div class="purchase-head"><div class="purchase-icon">${icon}</div><div><div class="purchase-name">${_naEsc(p.name)}</div><div class="purchase-meta">${_naEsc(p.sku)} · ${_naEsc(_naCategoryLabel(p.cat))} · ${_naEsc(a.rotation.label)}</div></div><span class="purchase-priority ${a.priority}">${_naEsc(a.priorityLabel)}</span></div><div class="purchase-metrics"><div class="purchase-metric"><span>Stock</span><strong>${_naEsc(stockLabel)}</strong></div><div class="purchase-metric"><span>Venta diaria</span><strong>${a.avg.toFixed(2)}</strong></div><div class="purchase-metric"><span>Cobertura</span><strong>${_naEsc(coverage)}</strong></div></div><div class="purchase-recommend"><strong>${_naEsc(purchaseLabel)}</strong><p>${_naEsc(a.reason)}${a.suggestedUnits>0?` Inversión estimada: ${fmt(a.investment)}.`:''}</p></div><div class="purchase-card-actions"><button class="purchase-detail-btn" onclick="_naF9OpenDetail('${idToken}')">📊 Evaluar compra</button><button class="purchase-edit-btn" onclick="_naF9EditProduct('${idToken}')">✏️ Producto</button></div></article>`;}
function _naF9RenderSuggestions(){const rows=_naF9Visible(),all=_naF9All(),summary=_naF9Summary(rows),body=document.getElementById('invBody'),cfg=_naF9Settings();if(!body)return;document.getElementById('invB4').textContent=all.filter(a=>a.need).length;body.innerHTML=`<tr><td colspan="6"><div class="purchase-summary"><div class="purchase-summary-card"><span>Reposición urgente</span><strong>${summary.urgent}</strong></div><div class="purchase-summary-card"><span>Alta rotación</span><strong>${summary.high}</strong></div><div class="purchase-summary-card"><span>Riesgo / vencimiento</span><strong>${summary.risk}</strong></div><div class="purchase-summary-card"><span>Inversión sugerida</span><strong>${fmt(summary.investment)}</strong></div></div><div class="purchase-toolbar"><div><label>Historial analizado</label><select onchange="_naF9SetSetting('historyDays',this.value)">${[30,60,90,180,365].map(n=>`<option value="${n}" ${cfg.historyDays===n?'selected':''}>${n} días</option>`).join('')}</select></div><div><label>Cobertura deseada</label><select onchange="_naF9SetSetting('coverageDays',this.value)">${[15,30,45,60,90].map(n=>`<option value="${n}" ${cfg.coverageDays===n?'selected':''}>${n} días</option>`).join('')}</select></div><div><label>Margen de seguridad</label><select onchange="_naF9SetSetting('safetyDays',this.value)">${[0,3,7,14,21].map(n=>`<option value="${n}" ${cfg.safetyDays===n?'selected':''}>${n} días</option>`).join('')}</select></div><button class="purchase-export" onclick="_naF9Export()">⬇️ Exportar sugerencias</button></div><div class="purchase-list">${rows.length?rows.map(_naF9Card).join(''):'<div class="purchase-empty">✅ No se encontraron productos que necesiten reposición con los filtros actuales.</div>'}</div><div class="purchase-note">La sugerencia es informativa. Se calcula con ventas no anuladas, stock actual, presentación de compra y vencimiento. No crea órdenes ni modifica el inventario. Productos sin historial suficiente se marcan para revisión manual.</div></td></tr>`;}
async function _naF9SetSetting(key,value){if(!['historyDays','coverageDays','safetyDays'].includes(key))return;const before=_naClone(appConfig.purchaseSuggestion||{}),bounds={historyDays:[30,365],coverageDays:[7,180],safetyDays:[0,60]},[min,max]=bounds[key];appConfig.purchaseSuggestion={..._naF9Settings(),[key]:Math.max(min,Math.min(max,_naInt(value)))};_naF9RenderSuggestions();const result=await saveAppState();if(!_naWasPersisted(result)){appConfig.purchaseSuggestion=before;_naF9RenderSuggestions();toast('No se pudo guardar la configuración de sugerencias','error');return;}toast('Parámetro de compra actualizado','success');}
function _naF9Projection(a){const rows=[];for(let month=1;month<=12;month++){const days=month*30,demand=a.avg*days,sellable=a.expiry===null?demand:a.avg*Math.max(0,Math.min(days,a.expiry-a.cfg.safetyDays)),status=a.expiry!==null&&a.expiry<days?'Vence antes':a.avg<=0?'Sin historial':'Proyección vigente';rows.push({month,demand,sellable,status});}return rows;}
function _naF9EditProduct(token){const id=decodeURIComponent(String(token||'')),p=productos.find(x=>String(x.id)===id);if(p)editProd(p.id);}
function _naF9OpenDetail(token){const id=decodeURIComponent(String(token||'')),p=productos.find(x=>String(x.id)===String(id));if(!p)return;const a=_naF9AnalyzeProduct(p),rows=_naF9Projection(a),detail=document.getElementById('purchaseSuggestionDetail');if(!detail)return;detail.dataset.productId=String(p.id);const purchaseLabel=a.suggestedUnits>0?`${Number(a.packages.toFixed(2))} ${_naF9PurchaseUnitLabel(a.unitPurchase)} (${Number(a.suggestedUnits.toFixed(2))} unidades)`:'Sin compra automática';detail.innerHTML=`<div class="purchase-detail-hero"><div><h3>${_naEsc(p.icon||'📦')} ${_naEsc(p.name)}</h3><p>${_naEsc(a.reason)} · Historial: ${a.cfg.historyDays} días.</p></div><div class="purchase-big"><strong>${_naEsc(purchaseLabel)}</strong><span>SUGERENCIA ACTUAL</span></div></div><div class="purchase-detail-grid"><div class="purchase-detail-box"><span>Stock actual</span><strong>${Number(a.stock.toFixed(3))}</strong></div><div class="purchase-detail-box"><span>Venta diaria</span><strong>${a.avg.toFixed(3)}</strong></div><div class="purchase-detail-box"><span>Cobertura</span><strong>${a.coverage===null?'—':a.coverage.toFixed(1)+' días'}</strong></div><div class="purchase-detail-box"><span>Vencimiento</span><strong>${a.expiry===null?'Sin fecha':a.expiry+' días'}</strong></div><div class="purchase-detail-box"><span>Presentación</span><strong>1 ${_naEsc(a.unitPurchase)} = ${a.factor} unidades</strong></div><div class="purchase-detail-box"><span>Inversión sugerida</span><strong>${fmt(a.investment)}</strong></div><div class="purchase-detail-box"><span>Ingreso potencial</span><strong>${fmt(a.potentialRevenue)}</strong></div><div class="purchase-detail-box"><span>Ganancia potencial</span><strong>${fmt(a.potentialProfit)}</strong></div></div><div class="purchase-sim"><strong>Simular otra cantidad</strong><div class="purchase-sim-grid"><div><label class="fl">Cantidad de ${_naEsc(_naF9PurchaseUnitLabel(a.unitPurchase))}</label><input id="purchaseSimulationQty" type="number" min="0" step="1" value="${Math.max(0,Math.round(a.packages))}" oninput="_naF9Simulate()"></div><div class="purchase-sim-result" id="purchaseSimulationResult">—</div></div></div><div class="purchase-projection"><table><thead><tr><th>Mes</th><th>Demanda estimada</th><th>Vendible antes de vencer</th><th>Estado</th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong>Mes ${r.month}</strong></td><td>${r.demand.toFixed(1)} u.</td><td>${r.sellable.toFixed(1)} u.</td><td>${_naEsc(r.status)}</td></tr>`).join('')}</tbody></table></div><div class="purchase-note">Una fecha de vencimiento lejana no convierte por sí sola una compra en mala inversión. El sistema compara la cantidad con el ritmo real de ventas y el capital necesario.</div>`;document.getElementById('mSugerenciaCompra').classList.add('open');_naF9Simulate();}
function _naF9Simulate(){const detail=document.getElementById('purchaseSuggestionDetail'),p=productos.find(x=>String(x.id)===String(detail?.dataset.productId)),result=document.getElementById('purchaseSimulationResult');if(!p||!result)return;const a=_naF9AnalyzeProduct(p),qty=Math.max(0,_naNumber(document.getElementById('purchaseSimulationQty')?.value)),units=qty*a.factor,capital=units*_naNumber(p.costo),revenue=units*_naNumber(p.precio),combined=a.stock+units,coverage=a.avg>0?combined/a.avg:null;let cls='good',message=`Compra evaluada: ${Number(units.toFixed(2))} unidades · capital ${fmt(capital)} · venta potencial ${fmt(revenue)}.`;if(qty<=0){cls='warn';message='No se ha indicado una compra.';}else if(a.avg<=0){cls='warn';message=`Sin historial suficiente. La compra inmovilizaría ${fmt(capital)} y debe revisarse manualmente.`;}else if(a.expiry!==null&&coverage>Math.max(0,a.expiry-a.cfg.safetyDays)){cls='bad';message=`Riesgo alto: el stock total duraría ${coverage.toFixed(1)} días y el margen seguro antes de vencer es ${Math.max(0,a.expiry-a.cfg.safetyDays)} días.`;}else if(a.packages>0&&qty>a.packages*1.5){cls='warn';message=`La cantidad supera ampliamente la sugerencia de ${a.packages.toFixed(2)} ${_naF9PurchaseUnitLabel(a.unitPurchase)}. Cobertura resultante: ${coverage.toFixed(1)} días.`;}else{message+=` Cobertura estimada: ${coverage?.toFixed(1)||'—'} días.`;}result.className=`purchase-sim-result ${cls}`;result.textContent=message;}
function _naF9Export(){const rows=_naF9Visible().map(a=>({Producto:a.product.name,SKU:a.product.sku,Stock:a.stock,Venta_diaria:Number(a.avg.toFixed(4)),Cobertura_dias:a.coverage===null?'':Number(a.coverage.toFixed(2)),Rotacion:a.rotation.label,Vencimiento_dias:a.expiry??'',Unidad_compra:a.unitPurchase,Factor_presentacion:a.factor,Presentaciones_sugeridas:Number(a.packages.toFixed(3)),Unidades_sugeridas:a.suggestedUnits,Inversion_estimada:Number(a.investment.toFixed(2)),Ganancia_potencial:Number(a.potentialProfit.toFixed(2)),Prioridad:a.priorityLabel,Motivo:a.reason}));if(!rows.length){toast('No hay sugerencias para exportar','error');return;}const name=`sugerencia_compra_${obtenerHoy()}`;try{if(typeof XLSX!=='undefined'&&XLSX.utils?.json_to_sheet){const wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(rows);XLSX.utils.book_append_sheet(wb,ws,'Sugerencias');XLSX.writeFile(wb,`${name}.xlsx`);toast('Sugerencias exportadas a Excel','success');return;}}catch(error){console.error('[Sugerencia de compra] Exportación',error);} _naExportRowsToCsv(rows,`${name}.csv`);toast('Sugerencias exportadas a CSV','success');}
const _naF9BaseInvBadges=invBadges;
invBadges=function(){_naF9BaseInvBadges();const badge=document.getElementById('invB4');if(badge)badge.textContent=_naF9All().filter(a=>a.need).length;};
const _naF9BaseInvRender=invRender;
invRender=function(){renderCategorySelects();if(invTab==='sugerencia'){invBadges();_naF9RenderSuggestions();return;}return _naF9BaseInvRender();};
// MEJORA FASE 9: normalizar la presentación de compra en datos antiguos sin borrar campos.
const _naF9BaseNormalizeData=_naNormalizeData;
_naNormalizeData=function(){_naF9BaseNormalizeData();productos=productos.map(p=>({...p,unidadCompra:_naClean(p.unidadCompra||(p.unidCaja?'caja':'unidad'))||'unidad',factorCompra:Math.max(.001,_naNumber(p.factorCompra,p.unidCaja||1))}));_naF9Settings();};
document.addEventListener('DOMContentLoaded',()=>{_naF9Settings();setTimeout(()=>{const badge=document.getElementById('invB4');if(badge)badge.textContent=_naF9All().filter(a=>a.need).length;},300);});
