// equivalence-lib.test.mjs — fingerprint diff self-test + known divergence
//
// OBJECTIVE_ID: FASE4-CHARACTERIZATION-BASELINE

import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import { analyzeAll } from '../characterization/lib/static-parse.mjs';
import { ensureBaselineFixture, readFixtureText, BASE_COMMIT, PRODUCT_BLOB } from '../characterization/lib/extract-baseline.mjs';
import { gitBlobSha1 } from '../characterization/lib/blob-hash.mjs';
import { collectNames, diffFingerprints } from './fingerprint-diff.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const WORKSPACE_ROOT = path.resolve(__dirname, '..', '..');
const WT_PATH = path.join(WORKSPACE_ROOT, 'CVV2.4_backup_antes_demo-1.html');
const EVIDENCE_DIR = path.join(WORKSPACE_ROOT, 'evidence', 'characterization');
const HISTORICAL_PATH = path.join(EVIDENCE_DIR, 'known-divergence-historical.json');

test('collectNames merges function defs, override finals and global lines', () => {
  const analysis = {
    functions: [
      { name: 'foo', kind: 'assign-function', line: 10 },
      { name: 'bar', kind: 'function-decl', line: 20 },
    ],
    overrideMap: { foo: { finalImplementation: 10 } },
    globals: [{ name: 'g1', kind: 'let', line: 5 }],
  };
  const names = collectNames(analysis);
  assert.deepEqual(names.foo, { functionDefs: [10], finalImplementation: 10, globalLines: [] });
  assert.deepEqual(names.bar, { functionDefs: [20], finalImplementation: null, globalLines: [] });
  assert.deepEqual(names.g1, { functionDefs: [], finalImplementation: null, globalLines: [5] });
});

test('diffFingerprints self-test: added/removed/changed are correct', () => {
  const A = {
    functions: [
      { name: 'foo', kind: 'assign-function', line: 10 },
      { name: 'bar', kind: 'function-decl', line: 20 },
      { name: 'onlyA', kind: 'function-decl', line: 30 },
      { name: 'multi', kind: 'assign-function', line: 40 },
      { name: 'multi', kind: 'assign-function', line: 41 },
    ],
    overrideMap: { foo: { finalImplementation: 10 }, multi: { finalImplementation: 41 } },
    globals: [
      { name: 'g1', kind: 'let', line: 5 },
      { name: 'gOnlyA', kind: 'let', line: 6 },
    ],
  };
  const B = {
    functions: [
      { name: 'foo', kind: 'assign-function', line: 10 },
      { name: 'bar', kind: 'function-decl', line: 21 },
      { name: 'onlyB', kind: 'function-decl', line: 50 },
      { name: 'multi', kind: 'assign-function', line: 40 },
      { name: 'multi', kind: 'assign-function', line: 41 },
    ],
    overrideMap: { foo: { finalImplementation: 10 }, multi: { finalImplementation: 41 } },
    globals: [
      { name: 'g1', kind: 'let', line: 5 },
      { name: 'gOnlyB', kind: 'let', line: 7 },
    ],
  };
  const diff = diffFingerprints(A, B);
  assert.deepEqual(diff.added, ['gOnlyB', 'onlyB']);
  assert.deepEqual(diff.removed, ['gOnlyA', 'onlyA']);
  assert.deepEqual(diff.changed, ['bar']);
});

test('known divergence: authorized baseline vs working tree (read-only, dual-mode)', () => {
  // Frozen historical divergence record (NEVER regenerated by this test).
  // This assertion pins the canonical value (35 removed / 29 changed) so the
  // historical artifact stays protected on ANY branch, including the canonical one.
  assert.ok(fs.existsSync(HISTORICAL_PATH), 'frozen historical divergence record must exist');
  const historical = JSON.parse(fs.readFileSync(HISTORICAL_PATH, 'utf8'));
  assert.strictEqual(historical.kind, 'HISTORICAL_WORKSPACE_DIVERGENCE', 'historical record kind');
  assert.strictEqual(historical.frozen, true, 'historical record must be frozen');
  assert.strictEqual(historical.record.diff.removed.length, 35, 'canonical: 35 removed functions');
  assert.strictEqual(historical.record.diff.changed.length, 29, 'canonical: 29 changed functions');
  assert.ok(historical.record.diff.removed.includes('_naV10ConfirmExpenseIntent'), '_naV10ConfirmExpenseIntent must remain in historical removed');

  ensureBaselineFixture();
  const baseline = analyzeAll(readFixtureText());

  // Read-only parse of the working tree product file (NOT the baseline).
  const wtBuffer = fs.readFileSync(WT_PATH);
  // Normalize EOL to LF before hashing: git stores canonical LF blobs, but the checkout may hold CRLF (autocrlf).
  const wtBlob = gitBlobSha1(Buffer.from(wtBuffer.toString('utf8').replace(/\r\n/g, '\n'), 'utf8'));
  // Expected working-tree blob computed dynamically from HEAD, instead of a hardcoded prefix,
  // so checkout integrity is validated on ANY branch (canonical or divergent).
  const expectedWtBlob = execFileSync(
    'git',
    ['rev-parse', 'HEAD:CVV2.4_backup_antes_demo-1.html'],
    { encoding: 'utf8' }
  ).trim();
  const wtAnalysis = analyzeAll(wtBuffer.toString('utf8'));

  const diff = diffFingerprints(baseline, wtAnalysis);

  assert.strictEqual(wtBlob, expectedWtBlob, 'working tree blob must equal the HEAD blob (checkout integrity)');

  // Dual-mode witness (canonical vs divergent):
  //   - Canonical branch (HEAD tree == authorized baseline 2dec6363): diff must be entirely
  //     empty and the witness records IDENTICAL_TO_BASELINE.
  //   - Divergent workspace (any other HEAD blob, e.g. 505859a): keep the historical
  //     assertions (non-empty diff, _naV10ConfirmExpenseIntent removed) and DIVERGES.
  const isCanonical = expectedWtBlob === '2dec6363d8aeef52da64ba60ac8eac8eb14f75f7';

  let result;
  let sourceBNote;
  if (isCanonical) {
    assert.strictEqual(diff.added.length, 0, 'canonical: added must be empty');
    assert.strictEqual(diff.removed.length, 0, 'canonical: removed must be empty');
    assert.strictEqual(diff.changed.length, 0, 'canonical: changed must be empty');
    result = 'IDENTICAL_TO_BASELINE';
    sourceBNote = 'working tree, identical to authorized baseline';
  } else {
    assert.ok(diff.added.length || diff.removed.length || diff.changed.length, 'diff must be non-empty');
    assert.ok(diff.removed.includes('_naV10ConfirmExpenseIntent'), '_naV10ConfirmExpenseIntent must be in removed (present in baseline, absent in working tree)');
    result = 'DIVERGES';
    sourceBNote = 'working tree, NO baseline';
  }

  const payload = {
    result,
    sourceA: { commit: BASE_COMMIT, blob: PRODUCT_BLOB, note: 'authorized baseline fixture' },
    sourceB: { path: 'CVV2.4_backup_antes_demo-1.html', blob: wtBlob, shortBlob: wtBlob.slice(0, 7), note: sourceBNote },
    diff,
    historicalReference: 'known-divergence-historical.json',
  };
  fs.mkdirSync(EVIDENCE_DIR, { recursive: true });
  fs.writeFileSync(path.join(EVIDENCE_DIR, 'known-divergence.json'), JSON.stringify(payload, null, 2) + '\n');
});
